name: python-ci

# Trigger the workflow for any push to the main branch or pull request
on:
    push:
        branches:
            - main
    pull_request:
          branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            # Step1: Check out the code from the repository
            - name: Check out code
              uses: actions/checkout@v2

            # Step2: Set up python environment
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.8'

            # Step3: Install dependencies
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            # Step4: Run tests
            - name: Run tests
              run: pytest
